"""add document_id, user_id to sessions and unique email to users

Revision ID: f780b74365ec
Revises: 
Create Date: 2026-09-26 18:39:13.268676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f780b74365ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('document_id', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_sessions_user_id_users'), 'sessions', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.alter_column('sessions', 'user_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint(op.f('fk_sessions_user_id_users'), 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'user_id')
    op.drop_column('sessions', 'document_id')
    # ### end Alembic commands ###
